- type: entity
  id: EchoBarmenKettleCircuit
  parent: BaseMachineCircuitboard
  name: kettle machine board
  description: A machine printed circuit board for a kettle.
  components:
    - type: MachineBoard
      prototype: EchoBarmenKettle
      stackRequirements:
        Glass: 1

- type: entity
  id: ElectricRangeMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: electric range machine board
  description: A machine printed circuit board for an electric range.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenElectricRange
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4
      tagRequirements:
        Igniter:
          amount: 1
          defaultPrototype: Igniter
